name: Generate Commit Summary with AI

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  ai-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install OpenAI package
        run: pip install openai

      - name: Analyze Changes and Generate Summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Verificar si hay más de un commit en el historial
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            # Detectar cambios en toda la carpeta 'Proyecto'
            DIFF=$(git diff HEAD~1 -- Proyecto)
            
            # Si DIFF no está vacío, procede
            if [ -n "$DIFF" ]; then
              echo "$DIFF" > diff.txt
              python Proyecto/generate_summary.py diff.txt > commit_summary.txt
              
              # Solo crear un commit si commit_summary.txt tiene contenido
              if [ -s commit_summary.txt ]; then
                COMMIT_MSG=$(cat commit_summary.txt)
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add .
                git commit -m "$COMMIT_MSG"
              else
                echo "No se detectaron cambios en diff.txt para generar un resumen."
              fi
            else
              echo "No se detectaron cambios en la carpeta 'Proyecto'."
            fi
          else
            echo "No hay suficientes commits para generar un diff."
          fi

      - name: Check for GitHub Actions Workflow Changes
        run: |
          # Verificar si hay más de un commit en el historial
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            ACTIONS_DIFF=$(git diff HEAD~1 -- .github/workflows)
            if [ -n "$ACTIONS_DIFF" ]; then
              echo "$ACTIONS_DIFF" > actions_diff.txt
              python Proyecto/generate_actions_recommendations.py actions_diff.txt > actions_recommendations.txt
            else
              echo "No se detectaron cambios en los flujos de trabajo de GitHub Actions."
            fi
          else
            echo "No hay suficientes commits para generar un diff en el flujo de trabajo."

      - name: Display Recommendations
        if: success()
        run: |
          if [ -s actions_recommendations.txt ]; then
            cat actions_recommendations.txt
          else
            echo "No hay recomendaciones para cambios en los flujos de trabajo de GitHub Actions."

      - name: Push changes
        if: success()  
        run: |
          git push origin main

